const data = {
  products: [
    {
      name: "Nike casual shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 1400,
      brand: "Nike",
      rating: 5.0,
      numReviews: 9,
      countInStock: 23,
      description: "Comfortable nike shirt",
      inFeatured: true,
      banner: "/images/banner.jpg",
    },
    {
      name: "Nike casual shoes",
      slug: "free-shoes",
      category: "Shoes",
      image: "/images/shoes1.png",
      price: 1400,
      brand: "Nike",
      rating: 5.0,
      numReviews: 9,
      countInStock: 23,
      description: "Comfortable nike shirt",
      inFeatured: true,
      banner: "/images/banner.jpg",
    },
    {
      name: "Nike casual shirt",
      slug: "free-shirt",
      category: "Shoes",
      image: "/images/shirt1.jpg",
      price: 1400,
      brand: "Nike",
      rating: 5.0,
      numReviews: 9,
      countInStock: 23,
      description: "Comfortable nike shirt",
      inFeatured: true,
      banner: "/images/banner.jpg",
    },
    {
      name: "Nike casual shirt",
      slug: "free-shirt",
      category: "Shoes",
      image: "/images/shirt1.jpg",
      price: 1400,
      brand: "Nike",
      rating: 5.0,
      numReviews: 9,
      countInStock: 23,
      description: "Comfortable nike shirt",
      inFeatured: true,
      banner: "/images/banner.jpg",
    },
    {
      name: "Nike casual shirt",
      slug: "free-shirt",
      category: "Shoes",
      image: "/images/shirt1.jpg",
      price: 1400,
      brand: "Nike",
      rating: 5.0,
      numReviews: 9,
      countInStock: 23,
      description: "Comfortable nike shirt",
      inFeatured: true,
      banner: "/images/banner.jpg",
    },
  ],
};

export default data;
